import { listLeads } from "@/lib/leads/store";
import { formatCompressorModel } from "@/lib/format";

export const runtime = "nodejs";

export async function GET() {
  const leads = await listLeads();
  const rows = [
    [
      "createdAt",
      "status",
      "customerRating",
      "companyName",
      "companyWebsite",
      "companyActivity",
      "contactName",
      "email",
      "emailOpenedAt",
      "emailOpenCount",
      "emailClickedAt",
      "emailClickCount",
      "reportDownloadedAt",
      "reportDownloadCount",
      "phone",
      "brand",
      "category",
      "ageBand",
      "nominalKw",
      "annualHours",
      "energyPriceHufKwh",
      "loadProfile",
      "preferVariableSpeed",
      "consentPrivacy",
      "consentMarketing",
      "recommendedModel",
      "recommendedNominalKw",
      "recommendedInputKw",
      "oldInputKw",
      "annualHufSaved",
      "monthlyHufSaved",
      "fiveYearHufSaved",
      "annualKwhSaved",
      "heatRecoveryEnabled",
      "heatRecoveryCompressorModel",
      "heatRecoveryCompressorNominalKw",
      "heatRecoveryRecoverableHeatKw",
      "heatRecoveryUsefulHeatKw",
      "heatRecoverySeasonalSavingsHuf",
      "heatRecoveryTheoreticalSavingsHuf",
      "heatRecoveryTheoreticalGasSavedM3",
      "heatRecoverySeasonalGasSavedM3",
      "heatRecoveryAnnualUsefulHeatKwh",
      "heatRecoveryAnnualUsefulHeatMj",
      "heatRecoveryHeatingMonths",
      "heatRecoveryHotWaterMonths",
      "heatRecoveryGasPriceHufPerM3",
      "priority",
      "leadScore",
      "leadScoreLabel",
      "machineCount",
      "utmSource",
      "utmMedium",
      "utmCampaign",
      "utmContent",
      "utmTerm",
      "gclid",
      "gbraid",
      "wbraid",
      "liFatId",
      "referrer"
    ],
    ...leads.map((lead) => [
      lead.createdAt,
      lead.status,
      lead.customerRating ? String(lead.customerRating) : "",
      lead.input.companyName,
      lead.input.companyWebsite ?? "",
      lead.input.companyActivity ?? "",
      lead.input.name ?? "",
      lead.input.email,
      lead.engagement.emailOpenedAt ?? "",
      String(lead.engagement.emailOpenCount),
      lead.engagement.emailClickedAt ?? "",
      String(lead.engagement.emailClickCount),
      lead.engagement.reportDownloadedAt ?? "",
      String(lead.engagement.reportDownloadCount),
      lead.input.phone ?? "",
      lead.input.brand,
      lead.input.category,
      lead.input.ageBand,
      String(lead.input.nominalKw),
      String(lead.input.annualHours),
      String(lead.input.energyPriceHufKwh),
      lead.input.loadProfile ?? "",
      lead.input.preferVariableSpeed ? "true" : "false",
      lead.input.consentPrivacy ? "true" : "false",
      lead.input.consentMarketing ? "true" : "false",
      formatCompressorModel(lead.result.recommendedModel),
      String(lead.result.recommendedModel.nominalKw),
      String(lead.result.recommendedModel.inputKw),
      String(lead.result.selectedLegacy.degradedInputKw),
      String(lead.result.annualHufSaved),
      String(lead.result.monthlyHufSaved),
      String(lead.result.fiveYearHufSaved),
      String(lead.result.annualKwhSaved),
      lead.result.heatRecovery ? "true" : "false",
      lead.result.heatRecovery ? lead.result.heatRecovery.compressorModelName : "",
      lead.result.heatRecovery ? String(lead.result.heatRecovery.compressorNominalKw) : "",
      lead.result.heatRecovery ? String(lead.result.heatRecovery.recoverableHeatKw) : "",
      lead.result.heatRecovery ? String(lead.result.heatRecovery.usefulHeatKw) : "",
      lead.result.heatRecovery ? String(lead.result.heatRecovery.seasonalSavingsHuf) : "",
      lead.result.heatRecovery ? String(lead.result.heatRecovery.theoreticalSavingsHuf) : "",
      lead.result.heatRecovery ? String(lead.result.heatRecovery.theoreticalGasSavedM3) : "",
      lead.result.heatRecovery ? String(lead.result.heatRecovery.seasonalGasSavedM3) : "",
      lead.result.heatRecovery ? String(lead.result.heatRecovery.annualUsefulHeatKwh) : "",
      lead.result.heatRecovery ? String(lead.result.heatRecovery.annualUsefulHeatMj) : "",
      lead.result.heatRecovery ? String(lead.result.heatRecovery.heatingMonths) : "",
      lead.result.heatRecovery ? String(lead.result.heatRecovery.hotWaterMonths) : "",
      lead.result.heatRecovery ? String(lead.result.heatRecovery.gasPriceHufPerM3) : "",
      lead.result.priority?.label ?? "",
      lead.result.leadScore ? String(lead.result.leadScore.score) : "",
      lead.result.leadScore?.label ?? "",
      lead.result.totalMachineCount ? String(lead.result.totalMachineCount) : "1",
      lead.input.tracking?.utmSource ?? "",
      lead.input.tracking?.utmMedium ?? "",
      lead.input.tracking?.utmCampaign ?? "",
      lead.input.tracking?.utmContent ?? "",
      lead.input.tracking?.utmTerm ?? "",
      lead.input.tracking?.gclid ?? "",
      lead.input.tracking?.gbraid ?? "",
      lead.input.tracking?.wbraid ?? "",
      lead.input.tracking?.liFatId ?? "",
      lead.input.tracking?.referrer ?? ""
    ])
  ];

  const csv = rows.map((row) => row.map(csvCell).join(",")).join("\n");

  return new Response(csv, {
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": "attachment; filename=csavarkompresszor-lead-cockpit.csv"
    }
  });
}

function csvCell(value: string) {
  return `"${value.replaceAll('"', '""')}"`;
}
